1.- Crear el diccionario "covid" a partir de la gráfica ( 10 paises con mas muertes por el COVID_19) <br>
key (llave):Paises  
value(valores): Número de fallecidos

<img src="imagenes/COVID.png" alt="REPO" width="500" title = "REPO"/>

In [1]:
paises=['Guatemala','Paraguay','Bolivia','Ecuador','Chile','Argentina','Colombia','Peru','Mexico','Brasil']
muertes=[11615,15633,18350,32134,36748,110966,124474,198031,255452,576645]

diccionario=dict(zip(paises,muertes))
print(diccionario)

{'Guatemala': 11615, 'Paraguay': 15633, 'Bolivia': 18350, 'Ecuador': 32134, 'Chile': 36748, 'Argentina': 110966, 'Colombia': 124474, 'Peru': 198031, 'Mexico': 255452, 'Brasil': 576645}


2. Muestre llaves y valores del dicionario covid.

In [6]:
print(diccionario.keys())

dict_keys(['Guatemala', 'Paraguay', 'Bolivia', 'Ecuador', 'Chile', 'Argentina', 'Colombia', 'Peru', 'Mexico', 'Brasil'])
dict_values([11615, 15633, 18350, 32134, 36748, 110966, 124474, 198031, 255452, 576645])


In [23]:
print(diccionario.values())

dict_values([11615, 15633, 18350, 32134, 36748, 110966, 124474, 210250, 255452, 576645, 14528])


3.- Actualice el diccionario covid ya que las ultimas noticias indican que en Uruguay aumento el número de fallecidos<br> 
por el COVID-19 en 14528 y Perú  en 210250.

In [12]:
diccionario['Uruguay']=14528
diccionario['Peru']=210250
print(diccionario)

{'Guatemala': 11615, 'Paraguay': 15633, 'Bolivia': 18350, 'Ecuador': 32134, 'Chile': 36748, 'Argentina': 110966, 'Colombia': 124474, 'Peru': 210250, 'Mexico': 255452, 'Brasil': 576645, 'Uruguay': 14528}


4.- Crear el diccionario "dic1" a partir de las listas:
+ lista1=[10, 20, 30] y 
+ lista2=[(1, 2 ,3),['Pedro',100],['control','educación']]


In [19]:
lista1=[10, 20, 30]
lista2=[(1, 2 ,3),['Pedro',100],['control','educación']]
dic1=dict(zip(lista1,lista2))
print(dic1)

{10: (1, 2, 3), 20: ['Pedro', 100], 30: ['control', 'educación']}


5.- Escriba el código que permita acceder a la cadena 'educación' del diccinario dic1.<br>



6.- Escriba el código que permita cambiar  la cadena 'Pedro' por 'Alfredo' en  diccinario dic1.

7.- Crear el diccionario "cod" a partir de las listas:<br>

Localidad = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca','La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo','Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa','Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas','Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy','Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena','Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja','Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos','Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui','Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo','Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen','San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande','Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos','Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza','Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia','Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin','Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo','Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo']<br>

<br> Cod_Postal=[15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046]<br>


8.- Cambiar el código postal de 'San Isidro' a 66666 y muestre el resultado.